resources:
  - name: concourse-docs-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/dev54321/React-Spring-data-rest.git

jobs:
  - name: job
    public: true
    plan:
      - get: concourse-docs-git
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: concourse-docs-git
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: maven }
          run:
            path: sh
            args: 
                - -c  
                - |
                  cd concourse-docs-git/React-spring-data-rest/tut-react-and-spring-data-rest-master/security/
                  mvn install 
